import React from "react";
import Navbar from "./NavbarComponent";
import Card from "./Card";
import "../scss/home.scss";

function App() {
  return (
    <div className="App">
      <Navbar />
      <div className="App-cardsContainer">
        <Card
          title="People"
          description="add, delete, edit, select people as well as filter by address and test result date"
          url="/people"
          queries={"1, 11, 14, 9"}
        />

        <Card
          title="Public Health Workers"
          description="add, delete, edit, select public health workers as well as filter by positive tests on specific dates"
          url="/publicHealthWorker"
          queries={"2, 16"}
        />

        <Card
          title="Facility"
          description="add, delete, edit, select facility as well as find workers who work there"
          url="/facility"
          queries={"3, 15, 12"}
        />

        <Card
          title="Region"
          description="add, delete, edit, select a region"
          url="/region"
          queries={"4, 13, 17"}
        />

        <Card
          title="GroupZone"
          description="add, delete, edit, select a groupzone"
          url="/groupZone"
          queries={"5"}
        />

        <Card
          title="Public health recommendation"
          description="add, delete, edit, select a HealthRecs"
          url="/healthRecs"
          queries={"6 ??? ask"}
        />

        <Card
          title="Add alert"
          description="add alert based on region"
          url="/addAlert"
          queries={"7"}
        />

        <Card
          title="FollowUp form"
          description="Positive test follow up form"
          url="/followUp"
          queries={"8"}
        />

        <Card
          title="All Messages"
          description="All messages within a specific period of time that were generated by the system"
          url="/allMessages"
          queries={"10"}
        />
      </div>
    </div>
  );
}

export default App;
